### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by rishimunjal** [GjjvdBurg/paper2remarkable#139]
I am running the p2r command on windows command line with a path to the pdf that exists. This is the last step of my program and I keep running into the FileNotFound error. I have verified that the file exists on the [FILEPATH].  Any help would be appreciated.

p2r -d C:\[FILEPATH]\puzzle.pdf

Fontconfig error: Cannot load default config file: No such file: (null)

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Scripts\p2r.exe\__main__.py", line 7, in <module>
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\site-packages\paper2remarkable\__main__.py", line 13, in main
    sys.exit(realmain())
             ^^^^^^^^^^
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\site-packages\paper2remarkable\ui.py", line 337, in main
    runner(args.input, filenames, options, debug=args.debug)
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\site-packages\paper2remarkable\ui.py", line 309, in runner
    prov.run(new_input, filename=filename)
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\site-packages\paper2remarkable\providers\_base.py", line 222, in run
    intermediate_fname = op(intermediate_fname)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\site-packages\paper2remarkable\providers\_base.py", line 154, in rewrite_pdf
    status = subprocess.call(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\[USERPROFILE]\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by GjjvdBurg** [comment]
Apologies for the delay on this one @rishimunjal. It's hard to tell from the error message, but the issue might be with the installation of Ghostscript. The `rewrite_pdf` function uses Ghostscript and the problem might be that the `gs` executable can not be found. Please check that you've installed Ghostscript correctly and that the `gs` command works on the command line. If Ghostscript is installed at a non-standard location, you can provide it with the `--gs` option to `p2r`.
