### ISSUE TITLE
Build not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by koddas** [GjjvdBurg/paper2remarkable#145]
Ubuntu switched to Python 3.12 with their 24.04 release. Unforunately, this means that m2r2 doesn't work anymore, as it's using a function that was removed in 3.12. Thus, the build fails on the _build docs_ step. I had a short go at the _sphinx_mdinclude_ package as a replacement, but to no avail. I'd be happy to help out, but I'm not familiar enough with the build process to see what could be used as a replacement. m2r2 hasn't been updated for over a year, so getting help from there seems to be a dead end.

Mandatory dump:

```bash
johan@ubuntu:~/git/remarkable/paper2remarkable$ make install
make -C './docs' clean && make -C './docs' man
make[1]: Går till katalogen ”/home/johan/git/remarkable/paper2remarkable/docs”
rm -rf /tmp/p2r_docs/
rm -f man.rst
rm -rf ./output
rm -rf _static
rm -rf .build
rm -f ../p2r.1
make[1]: Lämnar katalogen ”/home/johan/git/remarkable/paper2remarkable/docs”
make[1]: Går till katalogen ”/home/johan/git/remarkable/paper2remarkable/docs”
test -d /tmp/p2r_docs/ || python -m venv /tmp/p2r_docs/
source /tmp/p2r_docs//bin/activate && pip install m2r2
Collecting m2r2
  Using cached m2r2-0.3.3.post2-py3-none-any.whl.metadata (7.1 kB)
Collecting mistune==0.8.4 (from m2r2)
  Using cached mistune-0.8.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting docutils>=0.19 (from m2r2)
  Using cached docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Using cached m2r2-0.3.3.post2-py3-none-any.whl (11 kB)
Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Using cached docutils-0.21.2-py3-none-any.whl (587 kB)
Installing collected packages: mistune, docutils, m2r2
Successfully installed docutils-0.21.2 m2r2-0.3.3.post2 mistune-0.8.4
touch /tmp/p2r_docs//bin/activate
source /tmp/p2r_docs//bin/activate && m2r2 man.md
Traceback (most recent call last):
  File "/tmp/p2r_docs/bin/m2r2", line 5, in <module>
    from m2r2 import main
  File "/tmp/p2r_docs/lib/python3.12/site-packages/m2r2.py", line 16, in <module>
    from pkg_resources import get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
make[1]: *** [Makefile:37: man.rst] Fel 1
make[1]: Lämnar katalogen ”/home/johan/git/remarkable/paper2remarkable/docs”
make: *** [Makefile:46: docs] Fel 2
```

**Comment by GjjvdBurg** [comment]
Good catch, thanks! Fixed by removing the m2r2 dependency
