### ISSUE TITLE
Fails for local pdf

### ISSUE THREAD

**Issue by matthijsvk** [GjjvdBurg/paper2remarkable#21]
I try to upload a pdf I have locally on my computer, and get this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/p2r", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/__main__.py", line 12, in main
    sys.exit(realmain())
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/ui.py", line 96, in main
    url = follow_redirects(url)
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/utils.py", line 102, in follow_redirects
    req = requests.head(url, allow_redirects=False)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/home/user/document.pdf': No schema supplied. Perhaps you meant http:///home/user/document.pdf?
```

So it seems like it's trying to fetch it from online.

**Comment by matthijsvk** [comment]
I found it might be because the local pdf isn't seen in the Docker container.
normal command: `docker run --rm -v "/home/matthijsv/.rmapi:/home/user/.rmapi:rw" p2r --center -v $HOME/document.pdf`.

Instead if I mount the document in the Docker container using the 'v' option, it works:
`docker run --rm -v "/home/matthijsv/.rmapi:/home/user/.rmapi:rw" -v "$HOME/document.pdf":"/workspace/document.pdf" p2r --center -v -p "/folder_on_remarkable/document.pdf" `

**Comment by matthijsvk** [comment]
I have a directory on my local machine where I store my papers, and a script to monitor whenever I add papers to it.
The script then automatically uploads the paper to a folder on the Remarkable.

```
#!/bin/bash

# adapted from https://askubuntu.com/questions/893019/monitor-folder-and-run-command-if-there-is-a-file-there
# requires `sudo apt-get install inotify-tools`

# set path to watch
DIR="$HOME/Documents/literature"

# set path on ReMarkable to send papers to
RM_DIR="/Papers"

# watch continuously if file is added or moved to the monitored directory?
inotifywait -m -r -e moved_to -e create "$DIR" --format "%f" | while read f

do
    echo $f
    # check if the file is a PDF file
    if [[ $f = *.pdf ]] || [[ $f = *.PDF ]] ; then
      # if so, send to remarkable /Work/Papers/todo directory
      echo "sending $f to remarkable..."
      # needs to mount local file into docker container, otherwise it's not visible and can't be sent
      # also centers the paper
      docker run --rm -v "/home/$USER/.rmapi:/home/user/.rmapi:rw" -v "$DIR/$f":"/workspace/$f" p2r --center -v "/workspace/$f" -p "$RM_DIR"
      echo "sent!"
    fi
done
```

**Comment by GjjvdBurg** [comment]
Hi @matthijsvk, thank you for reporting this issue and thanks for your patience.

It's true that the error was due to the fact that the program can't find the file and therefore assumes it's a URL. In the latest commit this is now fixed and the program no longer defaults to a URL if it can't find the local file. I'll update the package asap.
