### ISSUE TITLE
ERROR: pdftk failed to compress the PDF file.

### ISSUE THREAD

**Issue by mr-ubik** [GjjvdBurg/paper2remarkable#49]
OS: Arch

```console-output
$ pdftk --version

pdftk port to java 3.1.0 a Handy Tool for Manipulating PDF Documents
Copyright (c) 2017-2018 Marc Vinyals - https://gitlab.com/pdftk-java/pdftk
Copyright (c) 2003-2013 Steward and Lee, LLC.
pdftk includes a modified version of the iText library.
Copyright (c) 1999-2009 Bruno Lowagie, Paulo Soares, et al.
This is free software; see the source code for copying conditions. There is
NO warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Installed via `pip install --user paper2remarkable`

```console-output
$ p2r https://arxiv.org/abs/2002.11523
Error: Unexpected Exception in open_reader()
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
        at java.util.ArrayList.get(ArrayList.java:435)
        at pdftk.com.lowagie.text.pdf.PdfReader$PageRefs.iteratePages(PdfReader.java:3425)
        at pdftk.com.lowagie.text.pdf.PdfReader$PageRefs.readPages(PdfReader.java:3256)
        at pdftk.com.lowagie.text.pdf.PdfReader$PageRefs.<init>(PdfReader.java:3226)
        at pdftk.com.lowagie.text.pdf.PdfReader$PageRefs.<init>(PdfReader.java:3204)
        at pdftk.com.lowagie.text.pdf.PdfReader.readPages(PdfReader.java:925)
        at pdftk.com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:523)
        at pdftk.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:172)
        at pdftk.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:161)
        at com.gitlab.pdftk_java.TK_Session.add_reader(TK_Session.java:127)
        at com.gitlab.pdftk_java.TK_Session.open_input_pdf_readers(TK_Session.java:243)
        at com.gitlab.pdftk_java.TK_Session.<init>(TK_Session.java:1218)
        at com.gitlab.pdftk_java.pdftk.main_noexit(pdftk.java:150)
        at com.gitlab.pdftk_java.pdftk.main(pdftk.java:128)
Error: Failed to open PDF file: 
   paper_removed.pdf
Errors encountered.  No output created.
Done.  Input errors, so no output created.
ERROR: pdftk failed to compress the PDF file.

If you think this might be a bug, please raise an issue on GitHub at:
https://github.com/GjjvdBurg/paper2remarkable
```

**Comment by GjjvdBurg** [comment]
Thanks for the report @mr-ubik! I'll take a look

**Comment by mr-ubik** [comment]
I have tried the script on several other papers, and it worked fine. That was the only one raising the error.

**Comment by GjjvdBurg** [comment]
Yeah, that particular PDF file has a nested pdf file inside it, which breaks the (admittedly fragile) code that tries to remove the arXiv stamp (which this file doesn't actually have). The solution is to make the "dearxiv" function more robust, but it's going to take some time.

In the meantime, you can of course download the file to your computer and then point `p2r` at it, which will treat it as a local file and bypass the "dearxiv" function. If you encounter any other arXiv papers with problems please let me know.

**Comment by GjjvdBurg** [comment]
Thanks again for the report @mr-ubik! I've just released an updated version of the package that fixes the problem.
